name: Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: mvn -B verify
      - run: npm ci
        working-directory: ts
      - run: npm test
        working-directory: ts
